token: "the_token"
start_msg: |
  Привет! Я - бот-помощник. Я помогу тебе получить подарок.
  Но для этого тебе нужно ответить на несколько вопросов.
  *Внимательно читай вопросы.*
correct_msg:
  - правильно
  - "ага. Читаю подсказку:"
incorrect_msg:
  - неправильно
  - эмм... точно нет
  - давай попробуем еще раз
end_msg: |
  Ура! Твой подарок уже ждет тебя в тайнике!
end_image: images/end.png # optional
questions:
  - question: Столица Армении?
    image: images/q0.png # optional
    answer: Ереван
  - question: Что больше, метр или километр?
    options: # optional
      - метр
      - километр
    answer: километр
